(cl:defpackage dynamixel_gripper-srv
  (:use )
  (:export
   "DUALGRIPPERGRASP"
   "<DUALGRIPPERGRASP-REQUEST>"
   "DUALGRIPPERGRASP-REQUEST"
   "<DUALGRIPPERGRASP-RESPONSE>"
   "DUALGRIPPERGRASP-RESPONSE"
   "GRIPPERCLOSE"
   "<GRIPPERCLOSE-REQUEST>"
   "GRIPPERCLOSE-REQUEST"
   "<GRIPPERCLOSE-RESPONSE>"
   "GRIPPERCLOSE-RESPONSE"
   "GRIPPEROPEN"
   "<GRIPPEROPEN-REQUEST>"
   "GRIPPEROPEN-REQUEST"
   "<GRIPPEROPEN-RESPONSE>"
   "GRIPPEROPEN-RESPONSE"
   "SINGLEGRIPPERGRASP"
   "<SINGLEGRIPPERGRASP-REQUEST>"
   "SINGLEGRIPPERGRASP-REQUEST"
   "<SINGLEGRIPPERGRASP-RESPONSE>"
   "SINGLEGRIPPERGRASP-RESPONSE"
  ))

