// Generated by gencpp from file lwr_ros_client/String_cmd.msg
// DO NOT EDIT!


#ifndef LWR_ROS_CLIENT_MESSAGE_STRING_CMD_H
#define LWR_ROS_CLIENT_MESSAGE_STRING_CMD_H

#include <ros/service_traits.h>


#include <lwr_ros_client/String_cmdRequest.h>
#include <lwr_ros_client/String_cmdResponse.h>


namespace lwr_ros_client
{

struct String_cmd
{

typedef String_cmdRequest Request;
typedef String_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct String_cmd
} // namespace lwr_ros_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lwr_ros_client::String_cmd > {
  static const char* value()
  {
    return "d4463b49bd5bb77dbd8c4356f5dc1c28";
  }

  static const char* value(const ::lwr_ros_client::String_cmd&) { return value(); }
};

template<>
struct DataType< ::lwr_ros_client::String_cmd > {
  static const char* value()
  {
    return "lwr_ros_client/String_cmd";
  }

  static const char* value(const ::lwr_ros_client::String_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::lwr_ros_client::String_cmdRequest> should match 
// service_traits::MD5Sum< ::lwr_ros_client::String_cmd > 
template<>
struct MD5Sum< ::lwr_ros_client::String_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lwr_ros_client::String_cmd >::value();
  }
  static const char* value(const ::lwr_ros_client::String_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lwr_ros_client::String_cmdRequest> should match 
// service_traits::DataType< ::lwr_ros_client::String_cmd > 
template<>
struct DataType< ::lwr_ros_client::String_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::lwr_ros_client::String_cmd >::value();
  }
  static const char* value(const ::lwr_ros_client::String_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lwr_ros_client::String_cmdResponse> should match 
// service_traits::MD5Sum< ::lwr_ros_client::String_cmd > 
template<>
struct MD5Sum< ::lwr_ros_client::String_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lwr_ros_client::String_cmd >::value();
  }
  static const char* value(const ::lwr_ros_client::String_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lwr_ros_client::String_cmdResponse> should match 
// service_traits::DataType< ::lwr_ros_client::String_cmd > 
template<>
struct DataType< ::lwr_ros_client::String_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::lwr_ros_client::String_cmd >::value();
  }
  static const char* value(const ::lwr_ros_client::String_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LWR_ROS_CLIENT_MESSAGE_STRING_CMD_H
