// Generated by gencpp from file dynamixel_gripper/DualGripperGrasp.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_GRIPPER_MESSAGE_DUALGRIPPERGRASP_H
#define DYNAMIXEL_GRIPPER_MESSAGE_DUALGRIPPERGRASP_H

#include <ros/service_traits.h>


#include <dynamixel_gripper/DualGripperGraspRequest.h>
#include <dynamixel_gripper/DualGripperGraspResponse.h>


namespace dynamixel_gripper
{

struct DualGripperGrasp
{

typedef DualGripperGraspRequest Request;
typedef DualGripperGraspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DualGripperGrasp
} // namespace dynamixel_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_gripper::DualGripperGrasp > {
  static const char* value()
  {
    return "f335b9ea2f9d5dd5fcf3d9c70616d213";
  }

  static const char* value(const ::dynamixel_gripper::DualGripperGrasp&) { return value(); }
};

template<>
struct DataType< ::dynamixel_gripper::DualGripperGrasp > {
  static const char* value()
  {
    return "dynamixel_gripper/DualGripperGrasp";
  }

  static const char* value(const ::dynamixel_gripper::DualGripperGrasp&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_gripper::DualGripperGraspRequest> should match 
// service_traits::MD5Sum< ::dynamixel_gripper::DualGripperGrasp > 
template<>
struct MD5Sum< ::dynamixel_gripper::DualGripperGraspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_gripper::DualGripperGrasp >::value();
  }
  static const char* value(const ::dynamixel_gripper::DualGripperGraspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_gripper::DualGripperGraspRequest> should match 
// service_traits::DataType< ::dynamixel_gripper::DualGripperGrasp > 
template<>
struct DataType< ::dynamixel_gripper::DualGripperGraspRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_gripper::DualGripperGrasp >::value();
  }
  static const char* value(const ::dynamixel_gripper::DualGripperGraspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_gripper::DualGripperGraspResponse> should match 
// service_traits::MD5Sum< ::dynamixel_gripper::DualGripperGrasp > 
template<>
struct MD5Sum< ::dynamixel_gripper::DualGripperGraspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_gripper::DualGripperGrasp >::value();
  }
  static const char* value(const ::dynamixel_gripper::DualGripperGraspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_gripper::DualGripperGraspResponse> should match 
// service_traits::DataType< ::dynamixel_gripper::DualGripperGrasp > 
template<>
struct DataType< ::dynamixel_gripper::DualGripperGraspResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_gripper::DualGripperGrasp >::value();
  }
  static const char* value(const ::dynamixel_gripper::DualGripperGraspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_GRIPPER_MESSAGE_DUALGRIPPERGRASP_H
