// Generated by gencpp from file dynamixel_gripper/DualGripperGraspRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_GRIPPER_MESSAGE_DUALGRIPPERGRASPREQUEST_H
#define DYNAMIXEL_GRIPPER_MESSAGE_DUALGRIPPERGRASPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_gripper
{
template <class ContainerAllocator>
struct DualGripperGraspRequest_
{
  typedef DualGripperGraspRequest_<ContainerAllocator> Type;

  DualGripperGraspRequest_()
    : position(0.0)  {
    }
  DualGripperGraspRequest_(const ContainerAllocator& _alloc)
    : position(0.0)  {
  (void)_alloc;
    }



   typedef float _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DualGripperGraspRequest_

typedef ::dynamixel_gripper::DualGripperGraspRequest_<std::allocator<void> > DualGripperGraspRequest;

typedef boost::shared_ptr< ::dynamixel_gripper::DualGripperGraspRequest > DualGripperGraspRequestPtr;
typedef boost::shared_ptr< ::dynamixel_gripper::DualGripperGraspRequest const> DualGripperGraspRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dynamixel_gripper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4e11b3af29ed247b2bd150d3f4540f9";
  }

  static const char* value(const ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4e11b3af29ed247ULL;
  static const uint64_t static_value2 = 0xb2bd150d3f4540f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_gripper/DualGripperGraspRequest";
  }

  static const char* value(const ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position\n\
";
  }

  static const char* value(const ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DualGripperGraspRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_gripper::DualGripperGraspRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_GRIPPER_MESSAGE_DUALGRIPPERGRASPREQUEST_H
