// Generated by gencpp from file dynamixel_gripper/GripperOpen.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_GRIPPER_MESSAGE_GRIPPEROPEN_H
#define DYNAMIXEL_GRIPPER_MESSAGE_GRIPPEROPEN_H

#include <ros/service_traits.h>


#include <dynamixel_gripper/GripperOpenRequest.h>
#include <dynamixel_gripper/GripperOpenResponse.h>


namespace dynamixel_gripper
{

struct GripperOpen
{

typedef GripperOpenRequest Request;
typedef GripperOpenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperOpen
} // namespace dynamixel_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_gripper::GripperOpen > {
  static const char* value()
  {
    return "bb1d916c0cb02d122a8698fce1017916";
  }

  static const char* value(const ::dynamixel_gripper::GripperOpen&) { return value(); }
};

template<>
struct DataType< ::dynamixel_gripper::GripperOpen > {
  static const char* value()
  {
    return "dynamixel_gripper/GripperOpen";
  }

  static const char* value(const ::dynamixel_gripper::GripperOpen&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_gripper::GripperOpenRequest> should match 
// service_traits::MD5Sum< ::dynamixel_gripper::GripperOpen > 
template<>
struct MD5Sum< ::dynamixel_gripper::GripperOpenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_gripper::GripperOpen >::value();
  }
  static const char* value(const ::dynamixel_gripper::GripperOpenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_gripper::GripperOpenRequest> should match 
// service_traits::DataType< ::dynamixel_gripper::GripperOpen > 
template<>
struct DataType< ::dynamixel_gripper::GripperOpenRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_gripper::GripperOpen >::value();
  }
  static const char* value(const ::dynamixel_gripper::GripperOpenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_gripper::GripperOpenResponse> should match 
// service_traits::MD5Sum< ::dynamixel_gripper::GripperOpen > 
template<>
struct MD5Sum< ::dynamixel_gripper::GripperOpenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_gripper::GripperOpen >::value();
  }
  static const char* value(const ::dynamixel_gripper::GripperOpenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_gripper::GripperOpenResponse> should match 
// service_traits::DataType< ::dynamixel_gripper::GripperOpen > 
template<>
struct DataType< ::dynamixel_gripper::GripperOpenResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_gripper::GripperOpen >::value();
  }
  static const char* value(const ::dynamixel_gripper::GripperOpenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_GRIPPER_MESSAGE_GRIPPEROPEN_H
