// Generated by gencpp from file dynamixel_gripper/GripperClose.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_GRIPPER_MESSAGE_GRIPPERCLOSE_H
#define DYNAMIXEL_GRIPPER_MESSAGE_GRIPPERCLOSE_H

#include <ros/service_traits.h>


#include <dynamixel_gripper/GripperCloseRequest.h>
#include <dynamixel_gripper/GripperCloseResponse.h>


namespace dynamixel_gripper
{

struct GripperClose
{

typedef GripperCloseRequest Request;
typedef GripperCloseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperClose
} // namespace dynamixel_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_gripper::GripperClose > {
  static const char* value()
  {
    return "bb1d916c0cb02d122a8698fce1017916";
  }

  static const char* value(const ::dynamixel_gripper::GripperClose&) { return value(); }
};

template<>
struct DataType< ::dynamixel_gripper::GripperClose > {
  static const char* value()
  {
    return "dynamixel_gripper/GripperClose";
  }

  static const char* value(const ::dynamixel_gripper::GripperClose&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_gripper::GripperCloseRequest> should match 
// service_traits::MD5Sum< ::dynamixel_gripper::GripperClose > 
template<>
struct MD5Sum< ::dynamixel_gripper::GripperCloseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_gripper::GripperClose >::value();
  }
  static const char* value(const ::dynamixel_gripper::GripperCloseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_gripper::GripperCloseRequest> should match 
// service_traits::DataType< ::dynamixel_gripper::GripperClose > 
template<>
struct DataType< ::dynamixel_gripper::GripperCloseRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_gripper::GripperClose >::value();
  }
  static const char* value(const ::dynamixel_gripper::GripperCloseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_gripper::GripperCloseResponse> should match 
// service_traits::MD5Sum< ::dynamixel_gripper::GripperClose > 
template<>
struct MD5Sum< ::dynamixel_gripper::GripperCloseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_gripper::GripperClose >::value();
  }
  static const char* value(const ::dynamixel_gripper::GripperCloseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_gripper::GripperCloseResponse> should match 
// service_traits::DataType< ::dynamixel_gripper::GripperClose > 
template<>
struct DataType< ::dynamixel_gripper::GripperCloseResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_gripper::GripperClose >::value();
  }
  static const char* value(const ::dynamixel_gripper::GripperCloseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_GRIPPER_MESSAGE_GRIPPERCLOSE_H
