// Generated by gencpp from file dynamixel_gripper/SingleGripperGraspResponse.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_GRIPPER_MESSAGE_SINGLEGRIPPERGRASPRESPONSE_H
#define DYNAMIXEL_GRIPPER_MESSAGE_SINGLEGRIPPERGRASPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_gripper
{
template <class ContainerAllocator>
struct SingleGripperGraspResponse_
{
  typedef SingleGripperGraspResponse_<ContainerAllocator> Type;

  SingleGripperGraspResponse_()
    : success(false)  {
    }
  SingleGripperGraspResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SingleGripperGraspResponse_

typedef ::dynamixel_gripper::SingleGripperGraspResponse_<std::allocator<void> > SingleGripperGraspResponse;

typedef boost::shared_ptr< ::dynamixel_gripper::SingleGripperGraspResponse > SingleGripperGraspResponsePtr;
typedef boost::shared_ptr< ::dynamixel_gripper::SingleGripperGraspResponse const> SingleGripperGraspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dynamixel_gripper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_gripper/SingleGripperGraspResponse";
  }

  static const char* value(const ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
";
  }

  static const char* value(const ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SingleGripperGraspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_gripper::SingleGripperGraspResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_GRIPPER_MESSAGE_SINGLEGRIPPERGRASPRESPONSE_H
